version: '2'

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - variable.env
  nginx:
    depends_on:
      - phpfpm
    image: nginx
    ports:
      - 80:80"
    restart: always
    working_dir: /var/www
    volumes:
      - ./wordpress:/var/www/
      - ./conf/nginx/wordpress.conf:/etc/nginx/conf.d/default.conf
  phpfpm:
    image: phalconphp/php-apache:ubuntu-16.04
    restart: always
    working_dir: /var/www
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/
    depends_on:
      - mysql

  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '9000:80'
    restart: always
    working_dir: /var/www/html