version: '2'

services:
  mysql:
    image: mysql
    restart: always
    env_file:
      - variable.env
  wordpress:
    depends_on:
      - mysql
    image: wordpress
    ports:
      - '9000:80'
    restart: always
    working_dir: /var/www/html